### ISSUE TITLE
Не удаляются композиции, помеченные дизлайком, из очереди

### ISSUE THREAD

**Issue by AlexanderShad** [Rirusha/Cassette#10]
Добра.
При прослушивании композиций в "Мне нравится", сталкнулся с тем, что если в процессе я нажимаю дизлайк, а потом следующая.. то рано или поздно он опять вернется и начнет играть песню дизлайк, ту которая не должна быть в мне нравится. 
При этом у меня закешырованы композиции..
Получается список не обновляется
Было бы прикольно, чтоб после нажатия дизлайк, был авто рефреш списка мне нравится и удаления из кеша композиции которая дизлайкнута

С уважением

**Comment by AlexanderShad** [comment]
удалил вешь кеш... закрыл приложение открыл приложение.. вроде из списка дизлайк песни ушли
попробовал без кешированных песен сделать дизлайк.. в списке песня осталась, закрыл открыл все норм
...
могу предположить, что почему-то не уходят из проигрывания кешированные песни

**Comment by Rirusha** [comment]
Сейчас при дизлайке трек не удаляется из очереди, а просто включается следующий. Очередь прослушивания не связана напрямую с обзором плейлиста, поэтому они могут иметь разное содержимое. Для обновления плейлиста, страницу нужно обновить.

В будущих релизах добавлю удаление из очереди, спасибо за ошибку.
Также будет добавлен менеджер контента, чтобы не нужно было обновлять страницы при изменениях внутри приложения, но потом.
