### ISSUE TITLE
Невозможность авторизации с помощью стороннего сервиса

### ISSUE THREAD

**Issue by ByloTonix** [Rirusha/Cassette#100]
В момент авторизации через корпоративную почту ВШЭ должно перекидывать на сайт вуза, однако в этот момент диалоговое окно крашится

https://github.com/Rirusha/Cassette/assets/64357478/7f164144-6256-4ef8-8acb-91d291b69ac6

**Comment by ByloTonix** [comment]
Проблема несильно серьёзная, так как можно авторизоваться с помощью QR-кода

**Comment by Rirusha** [comment]
Что пишет терминал при запуске через него?

**Comment by ByloTonix** [comment]
![image](https://github.com/Rirusha/Cassette/assets/64357478/d0ac310d-d104-4fc7-a49a-88cdc417ec98)

**Comment by Rirusha** [comment]
Нашел возможную причину бага, будет исправлено в 0.2.0

**Comment by Rirusha** [comment]
В версии 0.2.0 проблема будет исправлена
