### ISSUE TITLE
Не меняется фокус при старте приложения в первый раз 

### ISSUE THREAD

**Issue by Toxblh** [Rirusha/Cassette#11]
![image](https://github.com/Rirusha/Cassette/assets/2198153/18b75903-e99e-4dd4-a388-6bc8f2b8f16c)

**Comment by Rirusha** [comment]
Можете дополнить, в плане не меняется фокус?

**Comment by Toxblh** [comment]
При первом запуске на мобильном устройстве, я вижу только вот то что по центру, загрузочный спин. Хотя если открыть многозадачность, видно, что есть окно добавления учётной записи, но фокус на него не переключился почему-то. 

Возможно это приколы phosh

**Comment by Rirusha** [comment]
Будет "исправлено" с приходом новой версии libadwaita и button sheets, которые должны избавить приложения от модальных окон. То, как это будет: https://t.me/CassetteGNOME_Discussion/1878
