### ISSUE TITLE
Учитывать наличие трека в плейлисте при добавлении 

### ISSUE THREAD

**Issue by wavy-cat** [Rirusha/Cassette#116]
В плейлист можно добавить трек дважды и оно даже будет работать (до его удаления).

Версия приложения: `0.1.4` из Flathub.
Проблема есть в версии `0.2.0-dev.e9ff751`.

**Comment by Ampernic** [comment]
Это не баг данного приложения.
Это возможно и в офф приложении Яндекса на других устройствах.

**Comment by wavy-cat** [comment]
Офф. приложение и сайт такого не допускают т.к. показывают что трек уже добавлен в плейлист. При повторном нажатии оно удаляется из плейлиста, а не добавляется в него заново.
![image](https://github.com/Rirusha/Cassette/assets/52543076/98a97ba9-b49e-4142-b24e-da6de2678dca)

**Comment by Rirusha** [comment]
Moved to https://gitlab.gnome.org/Rirusha/Cassette/-/issues
