### ISSUE TITLE
Не правильно открывается контекстное если окно прижато к правому краю экрана

### ISSUE THREAD

**Issue by BartolomeyKant** [Rirusha/Cassette#117]
![cassette](https://github.com/Rirusha/Cassette/assets/34532252/ec3f26c3-2d4e-48fd-ae13-09f51b730a2c)
при нажатии на меню настройки звука, меню открывается где-то не там.
Такое повторяется если до края экрана места меньше чем нужно для меню, меню открывется не в границах основного окна.
Если справа поставить другое окно, то меню открывается нормально, но его верстка как-то съезжает чутка.
![cassette 2](https://github.com/Rirusha/Cassette/assets/34532252/d8c8931a-813a-49c1-9049-9bbd1ba49472)

Cassette 0.2.0 из AUR.
У меня wm Hyprland.
в конфигурации задан gap 5 px вокруг окна. Не знаю влияет это на меню или нет.
 
Два монитора, проблема повторяется на обоих
Один 3072x1920 с включенным скейлингом x2
Второй 1920x1080 без скейлинга

**Comment by Rirusha** [comment]
Предположу, что проблема в wm, так как в Plasma и GNOME такой проблемы нет.
