### ISSUE TITLE
mpris state trouble

### ISSUE THREAD

**Issue by 13werwolf13** [Rirusha/Cassette#118]
intermittent strange behavior of the playback status bar in kde plasma 6 and kde-connect

https://github.com/Rirusha/Cassette/assets/3271641/bd920764-db67-4ba9-a648-b50fb517bffb

https://github.com/Rirusha/Cassette/assets/3271641/02758dfd-6086-4259-b364-8e533711b2d0

**Comment by Rirusha** [comment]
Moved to https://gitlab.gnome.org/Rirusha/Cassette/-/issues
