### ISSUE TITLE
Отсутствует иконка приложения в Настройках -> Звук -> Уровни громкости

### ISSUE THREAD

**Issue by OlegShchavelev** [Rirusha/Cassette#12]
Отсутствует иконка приложения в уровнях громкости

![image](https://github.com/Rirusha/Cassette/assets/20732384/a4d54729-0a86-40e4-a12f-cd2868b0b4ca)

## Шаги к воспроизведению
Открыть Cassete и воспроизвести композиции
Открыть Настройки-> Звук -> Уровни громкости

## Информация о системе
ALT Regular Sisyphus x86_64
Kernel: 6.6.11-un-def-alt1
GNOME 45.2
AMD Ryzen 7 4800HS with Radeon Graphics (16) @ 4.300GHz
AMD ATI 04:00.0 Renoir
1: 1920x1080144Hz 2: 1280x72060Hz
Wayland

**Comment by skobkin** [comment]
Distro: Gentoo
Env: Flatpak
Version: Cassette 0.2.0
DE: Plasma 6.1.4, KDE Frameworks 6.5.0, Qt 6.7.2
Graphics: Wayland
![image](https://github.com/user-attachments/assets/ea1dc85f-0434-468a-82d2-cd8d241a2931)

**Comment by Rirusha** [comment]
Moved to https://gitlab.gnome.org/Rirusha/Cassette/-/issues
