### ISSUE TITLE
Звук 5.1

### ISSUE THREAD

**Issue by zhenyakoltsov** [Rirusha/Cassette#120]
У меня установлена акустическая система 5.1, звук в приложение работает только в двух передних колонках, хочется что звук работал в пяти колонках.

**Comment by Rirusha** [comment]
Должен ли звук идти из всех колонок? Не совсем понимаю, так как никогда не пользовался чем-то, отличным от 2.0. Попробую достать подобное для тестов

**Comment by zhenyakoltsov** [comment]
Звук в плеере VLC работает через 5 колонок, в браузерах на основе Chromium через 2 колонки, мне нужно приложение для прослушивания музыки через яндекс музыку которое сможет выводить звук через 5 колонок, если ваше приложение научится так работать я буду счастлив :-).

**Comment by Rirusha** [comment]
Moved to https://gitlab.gnome.org/Rirusha/Cassette/-/issues
