### ISSUE TITLE
implicit state of the like button

### ISSUE THREAD

**Issue by 13werwolf13** [Rirusha/Cassette#121]
Looking at the like button, it is not clear what state it is in without a tooltip.
in most applications (including the official android client Yandex music) if there is already a like, then the heart is filled, if there is no like, then the heart only has an outline.

![Screenshot_2024 07 22 01 37 14](https://github.com/user-attachments/assets/f0297438-2df7-4844-beee-036c8ba8bc2d)
in this screenshot a track is playing that already has a like mark, but the icon looks like it doesn’t exist, I always want to put a like, but this will remove the already existing like..

**Comment by Rirusha** [comment]
The problem is in your topic, you have two kinds of hearts. One with a wide outline, this is the application icon; the other is an empty heart with a thin outline, this is the system icon
