### ISSUE TITLE
Добавить приложение в репозиторий NixOS

### ISSUE THREAD

**Issue by BogusKladik** [Rirusha/Cassette#122]
Хотелось бы видеть данное приложение или в официальном репозитории дистрибутива NixOS, или в стороннем репозитории.

**Comment by nebulosa2007** [comment]
Уже есть pull request https://github.com/Rirusha/Cassette/pull/119

**Comment by averyanalex** [comment]
> Хотелось бы видеть данное приложение или в официальном репозитории дистрибутива NixOS, или в стороннем репозитории.

https://github.com/NixOS/nixpkgs/pull/326213

Уже в master, скоро будет в unstable

**Comment by BogusKladik** [comment]
Извиняюсь, не заметил
