### ISSUE TITLE
Исправить звук при перемотке музыки через ползунок

### ISSUE THREAD

**Issue by BogusKladik** [Rirusha/Cassette#127]
При перемотке звука через ползунок, можно услышать ~~9 кругов ада~~ весьма неприятный звук перемотки. По-идее, логически все верно, но такого звука слышать не хочется, ожидается либо отсутствие звука при перемотке, либо некое смягчение данного звука

**Comment by Rirusha** [comment]
Можете записать видео со звуком?

**Comment by BogusKladik** [comment]
> Можете записать видео со звуком?

https://disk.yandex.ru/i/NXwe_n_9KAbJ7A

**Comment by Rirusha** [comment]
Moved to https://gitlab.gnome.org/Rirusha/Cassette/-/issues
