### ISSUE TITLE
Проблема с авторизацией, не выдаёт редирект, а открывает веб версию я.музыки 

### ISSUE THREAD

**Issue by webtim1111** [Rirusha/Cassette#128]
Проблема с авторизацией, не выдаёт редирект, а открывает веб версию я.музыки 
![Снимок экрана от 2024-07-27 10-44-34](https://github.com/user-attachments/assets/e0580c59-96d6-483e-9269-61188f1d6764)

**Comment by Rirusha** [comment]
Попробуйте открыть ссылку:
```
https://oauth.yandex.ru/authorize?response_type=token&client_id=23cabbbdc6cd418abb4b39c32c41195d&https://music.yandex.ru
```
На какой сайт редиректит?

**Comment by Rirusha** [comment]
Вскоре обновится Devel версия. Проверьте, повторяется ли ошибка

**Comment by webtim1111** [comment]
> Попробуйте открыть ссылку:
> 
> ```
> https://oauth.yandex.ru/authorize?response_type=token&client_id=23cabbbdc6cd418abb4b39c32c41195d&https://music.yandex.ru
> ```
> 
> На какой сайт редиректит?

на я.музыку

**Comment by Rirusha** [comment]
> > Попробуйте открыть ссылку:
> > ```
> > https://oauth.yandex.ru/authorize?response_type=token&client_id=23cabbbdc6cd418abb4b39c32c41195d&https://music.yandex.ru
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > На какой сайт редиректит?
> 
> на я.музыку

Какая ссылка?

**Comment by WebDev2030** [comment]
У меня такая же проблема. При перезоде по ссылке открывается: https://music.yandex.kz/home (я из Казахстана)

**Comment by Rirusha** [comment]
> У меня такая же проблема. При перезоде по ссылке открывается: https://music.yandex.kz/home (я из Казахстана)

Воспроизводится ли проблема в Devel версии?

**Comment by Rirusha** [comment]
Moved to https://gitlab.gnome.org/Rirusha/Cassette/-/issues
