### ISSUE TITLE
Добавить фоновый режим

### ISSUE THREAD

**Issue by TeddyBatlink** [Rirusha/Cassette#129]
Отличное приложение, лично мне уже на данном этапе достаточно существующего функционала, кроме одного - работа в фоновом режиме, очень неудобно, когда при закрытии приложения оно не сворачивается в системный трей. Если есть такая возможность, то хорошо бы было этот режим добавить с переключателем в настройках (вдруг кому-то не нужен фоновый режим).

**Comment by Rirusha** [comment]
Инью уже есть #42

**Comment by Rirusha** [comment]
@Rirusha
