### ISSUE TITLE
Не работает поиск по "лупе"

### ISSUE THREAD

**Issue by AlexanderShad** [Rirusha/Cassette#130]
Добрый день.

По значку поиска (лупа) не происходит поиск треков,
как во flatpak так и в пакете на Альт Линукс

С уважением.

**Comment by AlexanderShad** [comment]
Разговор про глобальный поиск который с лева вверху

**Comment by Rirusha** [comment]
Глобальный поиск пока не реализован и не должен работать. Возможно клика по кнопке - баг. Исправлен в main ветке
