### ISSUE TITLE
Не играет музыка

### ISSUE THREAD

**Issue by fereline0** [Rirusha/Cassette#131]

**Comment by Rirusha** [comment]
Какой дистрибутив? Через что приложение было установлено?

**Comment by fereline0** [comment]
> Какой дистрибутив? Через что приложение было установлено?

Cachy os, hyprland, aur(yay)

**Comment by fereline0** [comment]
Соединение с интернетом есть, подборки грузятся, но песня не играет, слайдер показывает что она не проигывается, время не идет

**Comment by nebulosa2007** [comment]
Добавил необходимую зависимость в AUR, просьба обновиться

**Comment by Rirusha** [comment]
@fereline0, отпишитесь, если проблема ушла/осталась, пожалуйста

**Comment by fereline0** [comment]
> Добавил необходимую зависимость в AUR, просьба обновиться

Большое спасибо, все работает!

**Comment by fereline0** [comment]
Хотел также поинтересоваться, когда будет доступно примерно lossless качество?)

**Comment by Rirusha** [comment]
> Хотел также поинтересоваться, когда будет доступно примерно lossless качество?)

Относительно скоро
