### ISSUE TITLE
Add Lossless support

### ISSUE THREAD

**Issue by skobkin** [Rirusha/Cassette#132]
[Announce](https://habr.com/ru/news/837480/)

> 21 августа 2024 года в стриминговом сервисе «Яндекс Музыка» для подписчиков «Яндекс Плюса» стали доступны композиции в lossless-формате FLAC (Free Lossless Audio Codec).

> На первом этапе развёртывания этой опции подписчикам «Яндекс Музыка» доступно более 25 млн треков из каталога сервиса в lossless-формате.

> В мобильном и десктопном приложениях «Яндекс Музыки» теперь есть три режима прослушивания: «Превосходное», «Оптимальное» и «Экономичное».

**Comment by ProggerX** [comment]
ждем

**Comment by Rirusha** [comment]
Moved to https://gitlab.gnome.org/Rirusha/Cassette/-/issues
