### ISSUE TITLE
Не работает окно авторизации

### ISSUE THREAD

**Issue by SputnikFort** [Rirusha/Cassette#134]
![изображение](https://github.com/user-attachments/assets/c90b5eac-84f4-4dd2-9ffd-4d8b1a1480c9)
Содержимое внутри как бы есть, его можно поперетаскивать драгом, но на ощупь как то не логинится

Система: Arch linux, plasma6 x11

приложение установлено из yay

**Comment by fiersik** [comment]
@SputnikFort Важным дополнение было бы, какая видеокарта

Скорее всего Nvidia

Должно помочь 
WEBKIT_DISABLE_COMPOSITING_MODE=1 cassette

**Comment by SputnikFort** [comment]
спс
