### ISSUE TITLE
Plural-form being used for gender

### ISSUE THREAD

**Issue by rffontenelle** [Rirusha/Cassette#138]
The number of plural strings vary across languages. While English and Portuguese have only 2, other languages may have many numbers. So, using plural-form string to refer to male and female doesn't sound as a good idea.

Consider using 'msgctxt'. Message context enables exactly the same string to appear more than once in the translation file, but with different contexts. You could even include also a translation comment stating e.g. "%s is a female person" and "%s is male person" in each case.

For the record, GNOME uses msgctxt a lot to separate keyboard shortcut strings from other possibly equal strings in the same translation file.

https://github.com/Rirusha/Cassette/blob/1d6640be635d90ad0be8cfef9602a936dd7ac5dd/src/widgets/views/playlist.vala#L244-L248

**Comment by Rirusha** [comment]
https://github.com/Rirusha/Cassette/blob/343ef1b591553b4cba2dfc1279b3cbea87430492/src/widgets/cache-indicator/job-info-badge.vala#L74-L95

Will this fix the issue?

**Comment by Rirusha** [comment]
The dot is at the beginning of the second sequence for the sake of a single style. That is, the text does not end with a dot, the dot is just a separator. But I can suggest for the convenience of translators to make ". " as an untranslatable string. Then two quite logical sequences will remain for translators.

**Comment by rffontenelle** [comment]
That's a great alternative, thanks

**Comment by rffontenelle** [comment]
Only now I noticed we are discussing other issue in here. This one is about plural-form being used for genders.

**Comment by Rirusha** [comment]
> Only now I noticed we are discussing other issue in here. This one is about plural-form being used for genders.

I mixed up tabs with issues...
