### ISSUE TITLE
Bug: App crash if trying to play liked song without connection

### ISSUE THREAD

**Issue by Ampernic** [Rirusha/Cassette#141]
**Steps to reproduce:**
1. Clean cache
2. Close app
3. Disable network connections
4. Open app
5. Try to play "liked" song
6. Enjoy crash _and remove cassette_

**Demo**
https://github.com/user-attachments/assets/d67dedb0-f8e1-413a-95d6-0f8d56524c92

**Comment by Rirusha** [comment]
I will try to fix this with the first release of [libtape](https://github.com/Rirusha/libtape).

**Comment by Rirusha** [comment]
Moved to https://gitlab.gnome.org/Rirusha/Cassette/-/issues/141
