### ISSUE TITLE
Белое окно вместо окна авторизации

### ISSUE THREAD

**Issue by fereline0** [Rirusha/Cassette#142]
![image](https://github.com/user-attachments/assets/939be9a9-a137-4969-a06e-97eecd432ac3)

**Comment by fiersik** [comment]
@fereline0 Попробуйте это:

Если flatpak:
WEBKIT_DISABLE_COMPOSITING_MODE=1 flatpak run io.github.Rirusha.Cassette

Если нативная сборка:
WEBKIT_DISABLE_COMPOSITING_MODE=1 cassette
