### ISSUE TITLE
Изменить название приложения в соответствии с локалью рабочего окружения GNOME

### ISSUE THREAD

**Issue by OlegShchavelev** [Rirusha/Cassette#17]
Одна из новых черт рабочего окружения GNOME это локализация названия приложения в соответствии с локалью рабочего окружения. 
Предлагаю внедрить новый принцип:

RU - Кассета
EN - Cassette
BL - Касета

А к примеру когда появиться итальянский:cassetta )

**Comment by Rirusha** [comment]
Добавил комментарий к названию приложения в .desktop файле. Теперь всё в руках переводчиков
