### ISSUE TITLE
Невозможность запуска плейлиста сначала, если он уже играет

### ISSUE THREAD

**Issue by Leopoldium** [Rirusha/Cassette#18]
Мой режим прослушивания - "плейлист дня" от яндекса.
Этот плейлист меняется каждый день.  При запуске свежего листа проигрывает за предыдущий день. То-есть, с момента как остановился вчерашний. Переключение на следующий трек - продолжает двигаться по вчерашнему листу.

Решаю так - запускаю любой другой плейлист, после чего опять на плейлист дня. В этом случае уже играет новый.

Извиняюсь, если данный баг уже был.

flatpak info io.github.Rirusha.Cassette

Cassette - Неофициальный клиент сервиса Я.Музыка

              ID: io.github.Rirusha.Cassette
          Ссылка: app/io.github.Rirusha.Cassette/x86_64/stable
     Архитектура: x86_64
           Ветвь: stable
          Версия: 0.1.4

**Comment by Rirusha** [comment]
Спасибо за отзыв. Подумаю над тем, чтобы добавить кнопку "С начала" рядом с кнопкой "Play" у плейлиста.

**Comment by Rirusha** [comment]
Moved to https://gitlab.gnome.org/Rirusha/Cassette/-/issues
