### ISSUE TITLE
Не работает автоматическая промотка текста песни 

### ISSUE THREAD

**Issue by Seychik23** [Rirusha/Cassette#2]
Просмотр информации о треке выглядит неплохо, особенно для первой версии)). К сожалению, текст песни  автоматически не прокручивается в режиме караоке. 
![Снимок экрана от 2023-12-13 11-12-02](https://github.com/Rirusha/Cassette/assets/114060835/70a6631f-f8a0-4ed5-a819-262c88012523)

**Comment by Rirusha** [comment]
Полноценный режим караке будет в следующих версиях, сейчас он есть в месте с лириком, так как это удобно (на мой взгляд). Именно поэтому на флатхабе "караоке мод" в кавычках.
