### ISSUE TITLE
Всегда отображать кнопку скрытия/открытия sidebar с информацией о треке если активен плеер

### ISSUE THREAD

**Issue by Armatik** [Rirusha/Cassette#55]
Сейчас если открыть информацию о трэке появляется кнопка для скрытия sidebar с информацией о нём, после нажатия на которую она пропадает. Предлагаю оставлять эту кнопку видимой всегда, при условии активного плеера(есть выбранный трек для отображения информации).
![image](https://github.com/Rirusha/Cassette/assets/57626821/9383d489-22aa-468f-8224-f2cf4f16ebda)

**Comment by Rirusha** [comment]
Было реализовно немного иначе. Сейчас sidebar имеет свой заголовок с кнопкой скрытия. В заголовок основного окна кнопки не будут добавлять во избежания перегруженности и возможности сжатия окна.
