### ISSUE TITLE
Я не могу чисто физически авторизоваться

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [Rirusha/Cassette#6]
Я попытался войти, но в окне авторизации просто ничего нет, абсолютно ничего нет.

Arch Linux 6.6.6
Gnome
Закрытые драва Nvidia
![image](https://github.com/Rirusha/Cassette/assets/68144848/e7210df2-2589-41b0-a82b-27af266d7f7e)

**Comment by kray74** [comment]
Мне помогло добавление переменной окружения `WEBKIT_DISABLE_COMPOSITING_MODE=1` в /etc/environment.
Тоже Gnome и Nvidia, но на федоре. После добавления этой переменной заодно заработали Lutris и Gnome Yelp (справка)
