### ISSUE TITLE
Добавить возможно переключить на яндекс станцию и управлять ей

### ISSUE THREAD

**Issue by Toxblh** [Rirusha/Cassette#64]
Добавить локальное управление музыкой на колонках Яндекса. 
Данная функция есть в мобильном приложении, позволяющая "перекинуть" воспроизведение на устройство, а так же сменить устройство воспроизведения.

Для референса визуального можно использовать 

Кнопка справа в верху, открывает меню где играть
<p float="left">
<img src="https://github.com/Rirusha/Cassette/assets/2198153/5bb615ad-112e-4fa0-8d5e-e8d845292b3b" height="600">
<img src="https://github.com/Rirusha/Cassette/assets/2198153/b2afe428-2cac-43b2-aaf8-c69bf097ff46" height="600">
</p>

Так же пример, как это сделано у Spotify
<p float="left">
<img width="373" alt="image" src="https://github.com/Rirusha/Cassette/assets/2198153/c0641761-8bd0-4f4a-ab9a-c89b00ead758">
<img width="370" alt="image" src="https://github.com/Rirusha/Cassette/assets/2198153/fc421a2e-216f-4de8-8a81-87147616881d">
</p>

https://github.com/AlexxIT/YandexStation пример интеграции локального управления колонкой
Данная интеграция уже показывает, что играет и позволяет управлять колонкой
<img width="497" alt="image" src="https://github.com/Rirusha/Cassette/assets/2198153/642cef1c-f539-4f4f-bfc8-2a44c91ddfe4">

Задачки
- [ ] Получить и показать список устройств, а так же их текущий статус
- [ ] Возможность переключить на конкретное устройство
- [ ] Управлять воспроизведением на внешнем устройстве
- [ ] R&D возможности активировать Multiroom - играть музыку на всех доступных колонках одновременно
- [ ] Возможность "независимого" режима, когда не смотря на проигрывание музыки на колонке, дать возможность включить её на текущем устройстве (семья дома слушает, ты на работе с ноута)

**Comment by Rirusha** [comment]
Moved to https://gitlab.gnome.org/Rirusha/Cassette/-/issues
