### ISSUE TITLE
Работа с дизлайками

### ISSUE THREAD

**Issue by AlexanderShad** [Rirusha/Cassette#66]
Доброго времени суток.

При проигрывании музыки нажимаем "Поставить дизлайк" сердечко с песни снимается, включается следующая песня, но сама песня (которую дизлайкнули) не уходит из списка.

При проигрывании музыки нажимаем "Снять лайк" сердечко с песни снимается, следующая песня не включается, сама песня (которую дизлайкнули) не уходит из списка.

![cass](https://github.com/Rirusha/Cassette/assets/153871261/6316d9a4-7736-4f94-8c01-6d6005c42b73)

**Comment by Rirusha** [comment]
А в чем проблема? Вы описали нормальную работу приложения

**Comment by AlexanderShad** [comment]
Хм.. в моем понятии, при снятии лайка, должен быть эффект как при нажатии дизлайка, должно переходить на следующую песню, но и самое главное, песня со снятым сердцем должна уходить из плейлиста мне нравится

**Comment by Rirusha** [comment]
Нет, снятие лайка != дизлайк. Также песня не удаляется из списка до обновления, так как пользователь мог нажать случайно

**Comment by AlexanderShad** [comment]
Ok, но при клике на дизлайк она тоже не удаляется из списка сразу ) 
Я понял логику )

**Comment by Rirusha** [comment]
Для дизлайка свойственно удалять трек только из очереди

**Comment by AlexanderShad** [comment]
ок )
