### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by kerelape** [Rirusha/Cassette#68]
On Fedora 39 after the very first start the app requires to log in, but after a window with "Loading..." in the title appear nothing else happens. However if you move your pointer around you can notice, that the appearance of it changes like if there was a form to fill, but nothing is rendered.

**Comment by Rirusha** [comment]
Does the window contain anything? Is it empty or is the download constantly spinning in the middle?

**Comment by kerelape** [comment]
@Rirusha it's completely empty (except the header bar)

**Comment by Rirusha** [comment]
Do you have an nvidia graphics card? Is there the same problem in the GNOME browser, Epiphany?

**Comment by n6koma7a** [comment]
i have managed to launch it with
WEBKIT_DISABLE_COMPOSITING_MODE=1

there is an app which allows to control flatpack configuration called "Flatseal"
![Screenshot from 2024-03-27 02-04-29](https://github.com/Rirusha/Cassette/assets/143366711/82050d14-cafe-4b71-bf8f-c1c1928cf346)
