### ISSUE TITLE
Верстка модального окна | информацию об аккаунте

### ISSUE THREAD

**Issue by OlegShchavelev** [Rirusha/Cassette#7]
## Описание ошибки
Верстка текста не умещается в модальном окне 
![image](https://github.com/Rirusha/Cassette/assets/20732384/8ace095b-87e4-4ac9-a04c-e1e9f5d43006)

## Шаги к воспроизведению
1. Открыть приложение версию
2. Перенести приложение на экран с дробным масштабированием - 150%
3. Открыть информацию об аккаунте

## Информация о системе
- ALT Regular Sisyphus x86_64
- Kernel: 6.6.8-un-def-alt1 
- GNOME 45.2
- AMD Ryzen 7 4800HS with Radeon Graphics (16) @ 4.300GHz 
- AMD ATI 04:00.0 Renoir 
- 1: 1920x1080~144Hz 2: 1280x720~60Hz
- Wayland

**Comment by Rirusha** [comment]
Проблема всё ещё актуальна?

**Comment by fiersik** [comment]
@Rirusha Возможно
