### ISSUE TITLE
Исправить автоматический скип треков 

### ISSUE THREAD

**Issue by dant4ick** [Rirusha/Cassette#79]
Если убавить трек в приложении на минимум (выключить звук), треки начинают автоматичкески скипаться.

**Comment by Rirusha** [comment]
@dant4ick Ведет ли себя также devel версия?

**Comment by dant4ick** [comment]
Не могу проверить, девел поставить не получается по гайду, ошибка еще в разделе "Для разработчиков" 🥺🥺
![изображение](https://github.com/Rirusha/Cassette/assets/97320132/5368a2d7-e174-4fdc-ae1d-d031ef27a862)

**Comment by fiersik** [comment]
flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
flatpak install gnome-nightly org.gnome.Platform//master

**Comment by Rirusha** [comment]
@dant4ick, проблема есть в devel версии?

**Comment by dant4ick** [comment]
> @dant4ick, проблема есть в devel версии?

Нет, в devel все хорошо, этой ошибки нет, все огонь!
