### ISSUE TITLE
Отсутствие интерфейса при логине

### ISSUE THREAD

**Issue by DarkCloud894** [Rirusha/Cassette#81]
После нажатия на кнопку "log in" открывается пустое окно для авторизации
![Screenshot from 2024-03-24 18-23-11](https://github.com/Rirusha/Cassette/assets/66746779/4b14de74-b7d1-4079-a2e6-3c3d552b73f6)
При этом элементы интерфейса там есть (нажимаются, ссылка на главную страницу яндекса открывается),  но они не отображаются

**Comment by Rirusha** [comment]
@DarkCloud894 Здравствуйте, эта проблема описана в частых проблемах на странице wiki:
https://alt-gnome.wiki/cassette.html
