### ISSUE TITLE
Вылеты приложения

### ISSUE THREAD

**Issue by vadim212112** [Rirusha/Cassette#9]
Доброго времени. приложение интересное. давно ожидаемое многими.

При попытке скачать в кеш плейлист и при нажатии на его имя на вкладке плейлистов происходит вылет. в терминале следующее `cassette

(cassette:25409): Gtk-WARNING **: 15:44:53.967: AdwViewSwitcher 0x561a42199d40 (viewswitcher) reported min height -6, but sizes must be >= 0

(cassette:25409): Gtk-CRITICAL **: 15:46:26.986: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:26.986: Allocation width too small. Tried to allocate 431x651, but GtkOverlay 0x561a420aecc0 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:27.007: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:27.018: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:27.035: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:27.055: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:27.068: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:27.085: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:27.102: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:27.118: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:27.135: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:27.152: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.

(cassette:25409): Gtk-CRITICAL **: 15:46:27.168: Allocation width too small. Tried to allocate 431x651, but AdwBin 0x561a421a2a00 needs at least 470x651.
**
ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
Bail out! ERROR:arraylist.c:736:gee_array_list_real_get: assertion failed: (index < _size)
fish: Job 1, 'cassette' terminated by signal SIGABRT (Abort)
vadim@b560 ~ [SIGABRT]> 
`

Альт линукс сизиф кде

**Comment by Rirusha** [comment]
Проблема возможно будет исправлена в следующем обновлении (об этой проблеме известно, но ее тяжело воспроизвести)

**Comment by Katze-942** [comment]
Такая же проблема, похоже это проявляется когда слишком много треков в альбоме

**Comment by Rirusha** [comment]
Ошибка будет исправлена в версии 0.1.3
